### ISSUE TITLE
Kicad issues

### ISSUE THREAD

**Issue by johanliebs** [OLIMEX/ESP32-EVB#25]
Downloaded the Kicad files to have a look and I am getting errors opening the project, PCB layout and schematic files for both revisions D & F.

Project error: file '/home/johan/...Rev-F/NB-IoT-DevKit_RevB.pro',line 7:'=' expected

Ubuntu 18.04
Kicad 5.1.15 (also 5.02 before upgrade)

Thanks!

**Comment by DanKoloff** [comment]
Mmmm why does it say "Project error: file '...NB-IoT-DevKit_RevB.pro',line 7:'=' expected" - did you try to open NB-IoT-DevKit_RevB.pro project?

Edit: What is the full path to this file "NB-IoT-DevKit_RevB.pro"?

I assume you checked out something different there is no such file here: https://github.com/OLIMEX/ESP32-EVB/tree/master/HARDWARE/REV-F

**Comment by johanliebs** [comment]
At first I downloaded the ZIP file and extracted it to : /home/johan/kicad/olimex iot dev kit/Rev-F/. When I open the *.pro file:

![image](https://user-images.githubusercontent.com/30279849/70945291-97b06f00-20a0-11ea-9528-0e59fd9c70ac.png)

Second attempt is manually downloading each file from Rev-F (right click - save link as) to : /home/johan/kicad/olimex iot dev kit/Rev-F_manual_download/.  Same errors as the zip file.

![image](https://user-images.githubusercontent.com/30279849/70945363-bca4e200-20a0-11ea-89a6-9ead15b03e5b.png)

Also when I try to open any other file like the schematic, I get more errors. The 1st error:
![image](https://user-images.githubusercontent.com/30279849/70945667-6a17f580-20a1-11ea-93b1-6fa251dca9be.png)

But if I go to https://github.com/RevoluPowered/ESP32-EVB and do a ZIP download of Rev-D, Kicad opens the project just file without any errors.

![image](https://user-images.githubusercontent.com/30279849/70945798-a9dedd00-20a1-11ea-81cd-43f03bab2135.png)

**Comment by DanKoloff** [comment]
Can the issue be related to the path that you used to store the design files and which contains 3 x "space" character, namely "olimex iot dev kit"? One thing I've learned is that Linux doesn't like "space" character, let alone three of them.

If you look at the path of the successfully opening revision D files - there is no "space".

Re-downloaded and tested the design files on several machines here. No such issues here. And if I can't replicate it I can't fix it. 

It doesn't seem like a problem with our design sources, not only because we have no such issue but also no one else reported something similar and these files had been out for some time. Aside from placing the project in path without "space" character I'd also suggest, that it might be some specific issue with the KiCAD release for your operating system. I'd recommend re-installing KiCAD and maybe trying latest nightly build for your system. If the problem persists report it to the KiCAD team.

**Comment by johanliebs** [comment]
Removed all the spaces, made it simple, still the same error : 
![image](https://user-images.githubusercontent.com/30279849/71053013-dde8f980-2198-11ea-896e-cc4b195682ba.png)

**Comment by johanliebs** [comment]
I did another test with Kicad  4.0.6 on Mageia 6, which works fine without errors. Will try to re-install Kicad on Ubuntu 18.04

**Comment by johanliebs** [comment]
Same as before after un-installing and re-installing the latest version of Kicad on Ubuntu 18.04.... 

But if I go to https://github.com/RevoluPowered/ESP32-EVB and do a ZIP download of Rev-D, Kicad opens the project just file without any errors. Why would Rev-D work fine?

**Comment by TsvetanUsunov** [comment]
Hi
if you open the PCB file with text editor you will read this:
(kicad_pcb (version 20171130) (host pcbnew 6.0.0-rc1-unknown-0cca1c6~65~ubuntu16.04.1)
which means this file is made with KiCad PCB 6.0.0-rc1-unknown-0cca1c6~65~ubuntu16.04.1
you have to install same version of KiCad (hint read how to install the nightly builds) to may open and work with the file.
You try to open files made with 6.0 with KiCad 4 or 5 which is not possible.
